"""Update generated README result summaries from CSV outputs."""

from __future__ import annotations

import csv
import math
from pathlib import Path


START = "<!-- GENERATED_RESULTS_START -->"
END = "<!-- GENERATED_RESULTS_END -->"


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def _format_float(value: str) -> str:
    number = float(value)
    if math.isnan(number):
        return "nan"
    return f"{number:.4g}"


def build_results_summary(results_dir: Path = Path("results")) -> str:
    poisson_path = results_dir / "poisson_convergence.csv"
    heat_path = results_dir / "heat_convergence.csv"
    if not poisson_path.exists() or not heat_path.exists():
        return (
            "Current observed numerical results: pending. Run `make reproduce` in an "
            "environment with DOLFINx available to generate CSV files, figures, and this summary block."
        )

    poisson_rows = _read_csv(poisson_path)
    heat_rows = _read_csv(heat_path)
    lines = ["Observed numerical results from generated CSV files:"]

    for degree in sorted({row["degree"] for row in poisson_rows}, key=float):
        degree_rows = sorted(
            [row for row in poisson_rows if row["degree"] == degree],
            key=lambda row: float(row["h"]),
            reverse=True,
        )
        finite_rows = [row for row in degree_rows if row["L2_rate"] != "nan" and row["H1_rate"] != "nan"]
        if finite_rows:
            last = finite_rows[-1]
            lines.append(
                "- Poisson P"
                f"{int(float(degree))}: final adjacent L2 rate {_format_float(last['L2_rate'])}, "
                f"H1 seminorm rate {_format_float(last['H1_rate'])}."
            )

    if heat_rows:
        ordered_heat_rows = sorted(heat_rows, key=lambda row: float(row["h"]), reverse=True)
        first = ordered_heat_rows[0]
        last = ordered_heat_rows[-1]
        direction = "decreased" if float(last["final_L2_error"]) < float(first["final_L2_error"]) else "did not decrease"
        lines.append(
            "- Heat backward Euler: final-time L2 error "
            f"{direction} from {_format_float(first['final_L2_error'])} to {_format_float(last['final_L2_error'])} "
            "over the configured mesh/time refinements."
        )

    lines.append("All numbers in this block are regenerated by `scripts/reproduce_all.py`.")
    return "\n".join(lines)


def update_readme_results(readme_path: Path = Path("README.md"), results_dir: Path = Path("results")) -> None:
    text = readme_path.read_text(encoding="utf-8")
    if START not in text or END not in text:
        raise ValueError("README.md is missing generated-results markers")

    before, rest = text.split(START, 1)
    _, after = rest.split(END, 1)
    summary = build_results_summary(results_dir)
    readme_path.write_text(f"{before}{START}\n{summary}\n{END}{after}", encoding="utf-8")
